# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Gord Stephen 
tagline:          'Sociotechnical energy systems researcher'
description:      'Sociotechnical energy systems researcher and alumni of the <a href="https://uwaterloo.ca/sustainable-energy-policy/" target="_blank">Sustainable Energy Policy group</a> at the University of Waterloo.'
url:              http://www.gordstephen.ca
baseurl:          /

author:
  name:           'Gord Stephen'
  url:            'http://www.gordstephen.ca' 

# Custom vars
email:            'http://www.google.com/recaptcha/mailhide/d?k=01tG4h5A_4eXHg3FR7Rcjpeg==&c=GhqaUyineIlZOszOBIjYZhP2sboF9Tra3Xv3qqwiLE0='
github:           'https://github.com/GordStephen'
linkedin:         'https://www.linkedin.com/in/gordstephen'
stackexchange:    'http://stackexchange.com/users/3100373/gord-stephen?tab=accounts'

